MuseumWebApp/MuseumWebApp/MuseumWebApp/urls.py
"""
Definition of urls for MuseumWebApp.
"""

from datetime import datetime
from django.urls import re_path
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    re_path(r'^$', views.home, name='home'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^news/$', views.news, name='news'),
    re_path(r'^faq/$', views.faq, name='faq'),
    re_path(r'^faq/create_FAQ/$', views.create_FAQ, name='create_faq'),
    re_path(r'^faq/edit_FAQ/(?P<id>\d+)/$', views.edit_FAQ, name='edit_faq'),
    re_path(r'^home/excursion_detail/(?P<id>\d+)/$', views.excursion_detail, name='excursion_detail'),
    re_path(r'^home/exhibition_detail/(?P<id>\d+)/$', views.exhibition_detail, name='exhibition_detail'),
    re_path(r'^home/add_to_cart_excursion/(?P<id>\d+)/$', views.add_to_cart_excursion, name='add_to_cart_excursion'),
    re_path(r'^home/add_to_cart_exhibition/(?P<id>\d+)/$', views.add_to_cart_exhibition, name='add_to_cart_exhibition'),
    re_path(r'^faq/delete_FAQ/(?P<id>\d+)/$', views.delete_FAQ, name='delete_faq'),
    re_path(r'^contact/$', views.contact, name='contact'),
    re_path(r'^employee_list/$', views.employee_list, name='employee_list'),
    re_path(r'^contact/contact_delete/(?P<id>\d+)/$', views.contact_delete, name='contact_delete'),
    re_path(r'^vacancies/$', views.vacancies, name='vacancies'),
    re_path(r'^reviews/$', views.reviews, name='reviews'),
    re_path(r'^reviews/create_review/$', views.create_review, name='create_review'),
    re_path(r'^reviews/edit_review/(?P<id>\d+)/$', views.edit_review, name='edit_review'),
    re_path(r'^reviews/delete_review/(?P<id>\d+)/$', views.delete_review, name='delete_review'),
    re_path(r'^profile/(?P<id>\d+)/$', views.profile, name='profile'),
    re_path(r'^privacy-policy/$', views.privacy_policy, name='privacy_policy'),
    re_path(r'^promo_codes/$', views.promo_codes, name='promo_codes'),
    re_path(r'^promo_codes/create_promo_code/$', views.create_promo_code, name='create_promo_code'),
    re_path(r'^promo_codes/edit_promo_code/(?P<id>\d+)/$', views.edit_promo_code, name='edit_promo_code'),
    re_path(r'^promo_codes/delete_promo_code/(?P<id>\d+)/$', views.delete_promo_code, name='delete_promo_code'),
    re_path(r'^news/create_article/$', views.create_article, name='create_article'),
    re_path(r'^news/editArticle/(?P<id>\d+)/$', views.editArticle, name='edit_article'),
    re_path(r'^news/deleteArticle/(?P<id>\d+)/$', views.deleteArticle, name='delete_article'),
    re_path(r'^news/article_detail/(?P<id>\d+)/$', views.article_detail, name='article_detail'),
    re_path(r'^vacancies/create_job/$', views.create_job, name='create_job'),
    re_path(r'^vacancies/edit_job/(?P<id>\d+)/$', views.edit_job, name='edit_job'),
    re_path(r'^vacancies/delete_job/(?P<id>\d+)/$', views.delete_job, name='delete_job'),
    re_path(r'^about/edit_company_info/$', views.edit_company_info, name='edit_company_info'),
    re_path(r'^login/register/$', views.register, name='register'),
    re_path(r'^hall_info/$', views.hall_info, name='hall_info'),
    re_path(r'^newest_exhibits/$', views.newest_exhibits, name='newest_exhibits'),
    re_path(r'^employees_by_floor/$', views.employees_by_floor, name='employees_by_floor'),
    re_path(r'^exhibits_by_arrival_date/$', views.exhibits_by_arrival_date, name='exhibits_by_arrival_date'),
    re_path(r'^excursions_by_season/$', views.excursions_by_season, name='excursions_by_season'),
    re_path(r'^my_exhibits/$', views.my_exhibits, name='my_exhibits'),
    re_path(r'^my_excursions/$', views.my_excursions, name='my_excursions'),
    re_path(r'^all_excursions/$', views.all_excursions, name='all_excursions'),
    re_path(r'^my_tickets/$', views.my_tickets, name='my_tickets'),
    re_path(r'^my_cart/$', views.my_cart, name='my_cart'),
    re_path(r'^my_cart/pay_page/(?P<item_id>\d+)/$', views.pay_page, name='pay_page'),
    re_path(r'^my_cart/process_payment/(?P<item_id>\d+)/$', views.process_payment, name='process_payment'),
    re_path(r'^my_cart/remove_from_cart/(?P<item_id>\d+)/$', views.remove_from_cart, name='remove_from_cart'),
    re_path(r'^my_cart/decrease_quantity/(?P<item_id>\d+)/$', views.decrease_quantity, name='decrease_quantity'),
    re_path(r'^my_cart/increase_quantity/(?P<item_id>\d+)/$', views.increase_quantity, name='increase_quantity'),
    re_path(r'^all_exhibits/$', views.all_exhibits, name='all_exhibits'),
    re_path(r'^nationality/$', views.nationality_by_name, name='nationality_by_name'),
    re_path(r'^all_excursions/purchase_ticket_excursion/(?P<id>\d+)/$', views.purchase_ticket_excursion, name='purchase_ticket_excursion'),
    re_path(r'^all_exhibitions/$', views.all_exhibitions, name='all_exhibitions'),
    re_path(r'^all_exhibitions/purchase_ticket_exhibition/(?P<id>\d+)/$', views.purchase_ticket_exhibition, name='purchase_ticket_exhibition'),
    re_path(r'^excursions_by_season/excursion_delete/(?P<id>\d+)/$', views.excursion_delete, name='excursion_delete'),
    re_path(r'^excursions_by_season/excursion_edit/(?P<id>\d+)/$', views.excursion_edit, name='excursion_edit'),
    re_path(r'^create_excursion/$', views.create_excursion, name='create_excursion'),
    re_path(r'^newest_exhibits/create_new_exhibit/$', views.create_new_exhibit, name='create_new_exhibit'),
    re_path(r'^hall_detail/(?P<id>\d+)/$', views.hall_detail, name='hall_detail'),
    re_path(r'^hall_info/edit_hall/(?P<id>\d+)/$', views.edit_hall, name='edit_hall'),
    re_path(r'^hall_info/create_hall/$', views.create_hall, name='create_hall'),
    re_path(r'^hall_info/delete_hall/(?P<id>\d+)/$', views.delete_hall, name='delete_hall'),
    re_path(r'^hall_detail/(?P<id>\d+)/create_exhibit/$', views.create_exhibit, name='create_exhibit'),
    re_path(r'^hall_detail/(?P<id>\d+)/edit_exhibit/$', views.edit_exhibit, name='edit_exhibit'),
    re_path(r'^hall_detail/(?P<id>\d+)/delete_exhibit/$', views.delete_exhibit, name='delete_exhibit'),
    re_path(r'^statistics/$', views.statistics, name='statistics'),
    re_path(r'^article_all/(?P<id>\d+)/$', views.article_all, name='article_all'),
    path('certificate/', views.certificate_view, name='certificate_view'),
    re_path(
        r'^login/$',
        LoginView.as_view(
            template_name='app/login.html',
            authentication_form=forms.BootstrapAuthenticationForm,
            extra_context={
                'title': 'Log in',
                'year': datetime.now().year,
            }
        ),
        name='login'
    ),
    re_path(r'^logout/$', LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MuseumWebApp/MuseumWebApp/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    short_description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='articles/', blank=True, null=True)
    published_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title
    
class Banner(models.Model):
    image = models.ImageField(upload_to='banners/')
    alt_text = models.CharField(max_length=255, blank=True, null=True) 

    def __str__(self):
        return self.alt_text or "Without description"
    
class Partners(models.Model):
    name = models.CharField(max_length=255)
    logo = models.ImageField(upload_to='partners/')
    website = models.URLField()

    def __str__(self):
        return self.name

class CompanyInfo(models.Model):
    description = models.TextField()
    logo = models.ImageField(upload_to='company_logo/', blank=True, null=True)
    video = models.FileField(upload_to='company_videos/', blank=True, null=True)
    history = models.TextField(blank=True, null=True)
    details = models.TextField(blank=True, null=True)  
    banners = models.ManyToManyField(Banner, blank=True)  

    def __str__(self):
        return "Company Info"

class FAQ(models.Model):
    question = models.CharField(max_length=255)
    answer = models.TextField()
    added_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.question
    
class PrivacyPolicy(models.Model):
    content = models.TextField()

    def __str__(self):
        return "Privacy Policy"
    
class Job(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    requirements = models.TextField()
    salary = models.CharField(max_length=50)

    def __str__(self):
        return self.title
    
class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Review by {self.user.username}'

class PromoCode(models.Model):
    code = models.CharField(max_length=50)
    discount = models.DecimalField(max_digits=5, decimal_places=2)
    expiration_date = models.DateField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.code

class ArtType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Hall(models.Model):
    number = models.IntegerField(unique=True)
    name = models.CharField(max_length=100)
    floor = models.IntegerField()
    area = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.name} (Floor {self.floor})"
    
class Position(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    
class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, default='')
    last_name = models.CharField(max_length=100, default='')
    phone = models.CharField(max_length=15)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE, null=True, blank=True)
    photo = models.ImageField(upload_to='contact/', blank=True, null=True)
    email = models.EmailField(null=True, blank=True) 

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Exhibit(models.Model):
    name = models.CharField(max_length=200)
    art_type = models.ForeignKey(ArtType, on_delete=models.CASCADE)
    date_acquired = models.DateField()
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)
    caretaker = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True)
    image = models.ImageField(upload_to='articles/', blank=True, null=True)

    def __str__(self):
        return self.name
    
class Exhibition(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateField()
    end_date = models.DateField()
    exhibits = models.ManyToManyField(Exhibit)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name

class Excursion(models.Model):
    code = models.CharField(max_length=10, unique=True)
    name = models.CharField(max_length=200)
    date = models.DateField()
    season = models.CharField(max_length=10, choices=[('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter'), ('spring', 'Spring')])
    group_size = models.IntegerField()
    guide = models.ForeignKey(Employee, on_delete=models.SET_NULL, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.name
    
class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    
    quantity = models.PositiveIntegerField(default=1)
    added_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.content_object.name} x {self.quantity}"

    @property
    def total_price(self):
        return self.content_object.price * self.quantity
    
class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)

    def __str__(self):
        return f"Cart for {self.user.username}"

    @property
    def total_cost(self):
        return sum(item.total_price for item in self.items.all())
    
class Ticket_Excursion(models.Model):
    visitor = models.ForeignKey(User, on_delete=models.CASCADE)
    excursion = models.ForeignKey(Excursion, on_delete=models.CASCADE)
    purchase_date = models.DateField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Ticket for {self.excursion.name} by {self.visitor.username}"
    
class Ticket_Exhibition(models.Model):
    visitor = models.ForeignKey(User, on_delete=models.CASCADE)
    exhibition = models.ForeignKey(Exhibition, on_delete=models.CASCADE)
    purchase_date = models.DateField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Ticket for {self.exhibition.name} by {self.visitor.username}"

MuseumWebApp/MuseumWebApp/app/templates/app/all_excursions.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/all_excursions.css' %}">
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>

        <div class="excursions-form">
            <form method="GET" action="{% url 'all_excursions' %}">
                <label for="sort_by">Sort by:</label>
                <select id="sort_by" name="sort_by">
                    <option value="date_asc" {% if sort_by == 'date_asc' %}selected{% endif %}>Date (Ascending)</option>
                    <option value="date_desc" {% if sort_by == 'date_desc' %}selected{% endif %}>Date (Descending)</option>
                    <option value="name_asc" {% if sort_by == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                    <option value="name_desc" {% if sort_by == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                    <option value="price_asc" {% if sort_by == 'price_asc' %}selected{% endif %}>Price (Low to High)</option>
                    <option value="price_desc" {% if sort_by == 'price_desc' %}selected{% endif %}>Price (High to Low)</option>
                </select>
                <button type="submit" class="positive-button">Sort</button>
            </form>
        </div>


        {% if messages %}
        <div class="success-message">
            {% for message in messages %}
            <div>
                {{ message }}
            </div>
            {% endfor %}
        </div>
        {% endif %}


        {% if excursions %}
            <div class="excursion-list">
                {% for excursion in excursions %}
                <div class="excursion-card">
                    <h4>{{ excursion.name }} (Code: {{ excursion.code }})</h4>
                    <p><strong>Date:</strong> {{ excursion.date|date:"Y-m-d" }}</p>
                    <p><strong>Season:</strong> {{ excursion.get_season_display }}</p>
                    <p><strong>Group Size:</strong> {{ excursion.group_size }}</p>
                    <p><strong>Guide:</strong> {{ excursion.guide }}</p>
                    <p><strong>Price:</strong> {{ excursion.price }}</p>

                    {% if user.is_authenticated %}
                    {% if not is_employee and not user.is_superuser %}
                    <div class="buttons-top">
                        <a href="{% url 'add_to_cart_excursion' excursion.id %}" class="positive-button">Add To Cart</a>
                    </div>
                    {% endif %}
                    {% else %}
                    <p class="message">Please log in to purchase a ticket.</p>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        {% else %}
        <p class="message">No excursions found.</p>
        {% endif %}

    </div>
</body>
{% endblock %}

MuseumWebApp/MuseumWebApp/app/templates/app/all_exhibits.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/all_exhibits.css' %}">
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>

        <div class="exhibits-form">
            <form method="GET" action="{% url 'all_exhibits' %}">
                <label for="sort_by">Sort by:</label>
                <select id="sort_by" name="sort_by">
                    <option value="name_asc" {% if sort_by == 'name_asc' %}selected{% endif %}>Name (A-Z)</option>
                    <option value="name_desc" {% if sort_by == 'name_desc' %}selected{% endif %}>Name (Z-A)</option>
                    <option value="date_asc" {% if sort_by == 'date_asc' %}selected{% endif %}>Date Acquired (Old to New)</option>
                    <option value="date_desc" {% if sort_by == 'date_desc' %}selected{% endif %}>Date Acquired (New to Old)</option>
                    <option value="hall_asc" {% if sort_by == 'hall_asc' %}selected{% endif %}>Hall (A-Z)</option>
                    <option value="hall_desc" {% if sort_by == 'hall_desc' %}selected{% endif %}>Hall (Z-A)</option>
                </select>
                <button type="submit" class="positive-button">Sort</button>
            </form>
        </div>

        {% if exhibits %}
            <div class="exhibit-list">
                {% for exhibit in exhibits %}
                <div class="exhibit-card">
                    {% if exhibit.image %}
                    <img src="{{ exhibit.image.url }}" alt="{{ exhibit.name }}">
                    {% else %}
                    <img src="/static/images/default_exhibit.jpg" alt="{{ exhibit.name }}">
                    {% endif %}

                    <h4>{{ exhibit.name }}</h4>
                    <p><strong>Art Type:</strong> {{ exhibit.art_type }}</p>
                    <p><strong>Hall:</strong> {{ exhibit.hall }}</p>
                    <p><strong>Date Acquired:</strong> {{ exhibit.date_acquired }}</p>
                    <p><strong>Caretaker:</strong> {{ exhibit.caretaker }}</p>
                </div>
                {% endfor %}
            </div>
        {% else %}
        <p class="message">No exhibits found.</p>
        {% endif %}
    </div>
</body>
{% endblock %}

MuseumWebApp/MuseumWebApp/app/templates/app/create_promo_code.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/create_promocode.css' %}">
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>

        <form method="POST" class="promocode-form">
            {% csrf_token %}

            <div class="div-between-button">
                <label for="code" class="label-areas">Code:</label>
                <input type="text" id="code" name="code" class="input-areas" required>
            </div>

            <div class="div-between-button">
                <label for="discount" class="label-areas">Discount:</label>
                <input type="number" step="0.01" id="discount" name="discount" min="0" max="100" class="input-areas" required>
            </div>

            <div class="div-between-button">
                <label for="expiration_date" class="label-areas">Expiration Date:</label>
                <input type="date" id="expiration_date" name="expiration_date" class="input-areas" required>
            </div>

            <div class="button-align">
                <button type="submit" class="positive-button">
                    Submit
                </button>
            </div>
        </form>
    </div>
</body>
{% endblock %}

MuseumWebApp/MuseumWebApp/app/templates/app/edit_exhibit.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/create_exhibit.css' %}">
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>

        <form method="POST" class="exhibit-form" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="div-between image-position">
                <label for="image">Image</label>
                <div>
                    {% if exhibit.image %}
                    <img id="image-preview" src="{{ exhibit.image.url }}" alt="{{ exhibit.name }}">
                    {% else %}
                    <img id="image-preview" src="" alt="No image">
                    {% endif %}
                </div>
                <input type="file" id="image" name="image" class="input-areas">
            </div>

            <div class="div-between">
                <label for="name">Name</label>
                <input type="text" id="name" name="name" value="{{ exhibit.name }}" class="input-areas" required>
            </div>

            <div class="div-between">
                <label for="date_acquired">Date Acquired</label>
                <input type="date" id="date_acquired" name="date_acquired" value="{{ exhibit.date_acquired|date:'Y-m-d' }}" class="input-areas" required>
            </div>

            <div class="div-between">
                <label for="art_type">Art Type</label>
                <select id="art_type" name="art_type" class="input-areas">
                    {% for art_type in art_types %}
                    <option value="{{ art_type.id }}" {% if art_type.id == exhibit.art_type.id %}selected{% endif %}>{{ art_type.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="div-between">
                <label for="hall">Hall</label>
                <select id="hall" name="hall" class="input-areas">
                    {% for hall in halls %}
                    <option value="{{ hall.id }}" {% if hall.id == exhibit.hall.id %}selected{% endif %}>{{ hall.name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="div-between">
                <label for="caretaker">Caretaker</label>
                <select id="caretaker" name="caretaker" class="input-areas">
                    {% for caretaker in caretakers %}
                    <option value="{{ caretaker.id }}" {% if caretaker.id == exhibit.caretaker.id %}selected{% endif %}>{{ caretaker.first_name }} {{ caretaker.last_name }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="button-align">
                <button type="submit" class="positive-button">
                    Save changes
                </button>
            </div>

            {% if messages %}
            <div>
                {% for message in messages %}
                <div class="message" style="
                        {% if message.tags == 'error' %}background-color: #f89cff; color: white;{% else %}background-color: #d4edda; color: #155724;{% endif %}">
                    {{ message }}
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </form>
    </div>
</body>

{% endblock %}

MuseumWebApp/MuseumWebApp/app/templates/app/edit_promo_code.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/create_promocode.css' %}">
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>
            <form method="POST" class="promocode-form">
                {% csrf_token %}

                <div class="div-between-button">
                    <label for="code" class="label-areas">Code:</label>
                    <input type="text" id="code" name="code" class="input-areas" value="{{ promo_code.code }}" required>
                </div>

                <div class="div-between-button">
                    <label for="discount" class="label-areas">Discount:</label>
                    <input type="number" step="0.01" id="discount" name="discount" min="0" max="5" class="input-areas" value="{{ promo_code.discount }}" required>
                </div>

                <div class="div-between-button">
                    <label for="expiration_date" class="label-areas">Expiration Date:</label>
                    <input type="date" id="expiration_date" name="expiration_date" class="input-areas" value="{{ promo_code.expiration_date|date:'Y-m-d' }}" required>
                </div>

                <div class="button-align">
                    <button type="submit" class="positive-button">
                        Submit
                    </button>
                </div>
            </form>
    </div>
</body>

{% endblock %}

MuseumWebApp/MuseumWebApp/app/templates/app/exhibition_detail.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/exhibition_detail.css' %}">
    <title>{{ title }}</title>
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>

        {% if exhibition %}
        <div class="exhibition-content">
            <div class="exhibition-card">
                <h4>{{ exhibition.name }}</h4>
                <div class="center-text">
                    <p><strong>Start Date:</strong> {{ exhibition.start_date|date:"Y-m-d" }}</p>
                    <p><strong>End Date:</strong> {{ exhibition.end_date|date:"Y-m-d" }}</p>
                    <p><strong>Price:</strong> {{ exhibition.price }}</p>
                </div>

                <h3>Exhibits:</h3>
                <div id="show_from_id">
                    {% for exhibit in exhibition.exhibits.all %}
                    <div id="exhibit_info">
                        <div>
                            <p id="exhibit_name">{{ exhibit.name }}</p>
                            <p><strong>Art Type:</strong> {{ exhibit.art_type }}</p>
                            <p><strong>Date Acquired:</strong> {{ exhibit.date_acquired }}</p>
                        </div>

                        {% if exhibit.image %}
                        <div id="exhibit_photo">
                            <img src="{{ exhibit.image.url }}" alt="{{ exhibit.name }}">
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>

                {% if user.is_authenticated %}
                {% if not is_employee %}
                <div class="buttons-top">
                    <a href="{% url 'add_to_cart_exhibition' exhibition.id %}" class="positive-button">Add To Cart</a>
                </div>
                {% endif %}
                {% else %}
                <p class="message">Please log in to add to cart a ticket.</p>
                {% endif %}
                {% if messages %}
                <div class="success-message">
                    {% for message in messages %}
                    <div>
                        {{ message }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
        {% else %}
        <p class="message">No exhibition found.</p>
        {% endif %}
    </div>
</body>
{% endblock %}

MuseumWebApp/MuseumWebApp/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'app/content/login.css' %}">
</head>

<body>
    <div class="container-box">
        <h1>{{ title }}</h1>

        <form action="." method="post" class="login-form">
            {% csrf_token %}

            <div class="div-between-button">
                <label for="id_username">User name</label>
                <input type="text" id="id_username" name="username" class="input-areas">
            </div>

            <div class="div-between-button">
                <label for="id_password">Password</label>
                <input type="password" id="id_password" name="password" class="input-areas">
            </div>

            <div class="button-align">
                <button type="submit" class="positive-button">
                    Log In
                </button>
            </div>

            <div class="button-align">
                <a href="register/" class="positive-button change-color">Create an account</a>
            </div>

            {% if form.errors %}
            <p class="message">Please enter a correct user name and password.</p>
            {% endif %}
        </form>
    </div>
</body>
{% endblock %}